### ISSUE TITLE
License

### ISSUE THREAD

**Issue by Dutch-0** [JulienPalard/grid-finder#2]
I know this project is not maintained any more, but would it be possible to maybe add a licence file? Otherwise it legally cannot be used by others, which is really a shame for this amazing project.

**Comment by JulienPalard** [comment]
> Otherwise it legally cannot be used by others

This is wrong.

Without a licence file the project is protected by the Berne convention so the author holds the copyright and that's it, no restriction apply (except you can't modify it, but you can distribute the original along with patches, so distributing the original git repo + commits would be OK as I understand it).

https://en.wikipedia.org/wiki/License-free_software

But if you prefer, or live in a country with a law I don't understand (there's hundreds, IANAL), I'll gladly add a licence file for your safety or comfort.

**Comment by Dutch-0** [comment]
> Without a licence file the project is protected by the Berne convention so the author holds the copyright and that's it, no restriction apply (except you can't modify it, but you can distribute the original along with patches, so distributing the original git repo + commits would be OK as I understand it).
> 
> https://en.wikipedia.org/wiki/License-free_software

That is actually a good and interesting read, thank you.
As far as I understand this link: [IHK Stuttgart (German)](https://www.ihk.de/stuttgart/fuer-unternehmen/recht-und-steuern/it-recht/ueberlassung-von-standardsoftware-das-sind-die-regeln-4368114) , in Germany every code is protected: therefore requiring a licence.

**Comment by JulienPalard** [comment]
Here you go with an MIT License.

Don't hesitate to fork it, don't hesitate to open PR if you find issues/enhancements.

As you see I have no use of this lib so I don't actively maintain it. In the other hand it means you can change things without breaking anything ;)
